# Site settings
title: Flanders
client:
  name: Visit Flanders
  link: https://www.visitflanders.com/en/?country=en_GB
core-se-link: https://www.secretescapes.com/current-sales
description: >
  This fascinating Belgian region is brimming with history, art and culture, foodie treats and more. It is without doubt, unique; a perfect landscape for savvy travellers.

# file paths
url:     "http://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/flanders" # the subpath of your site, e.g. /blog/
img:     "/flanders/_assets/img"
css:     "/flanders/_assets/css"
js:      "/flanders/_assets/js"


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed